# Generated by Django 5.1.1 on 2024-09-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='purpose',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
